
services:

  rustimshub:
    image: matteolacki/rustims:latest
    hostname: rustims
    volumes:
      - "./inputs:/rustims/inputs"
    environment:
      - HOME=/rustims
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - "8888:8888"


  rustimshub_arm64:
    image: matteolacki/rustims_arm64:latest
    hostname: rustims
    volumes:
      - "./inputs:/rustims/inputs"
    environment:
      - HOME=/rustims
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - "8888:8888"

